# Setup
title: TITLE
description: SUB TITLE
url: https://github.com/RiaMedInfo/my-blog
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

lang: en

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Riya
  url: https://github.com/RiaMedInfo
  email: sotiriastriou@gmail.com
