# Setup
title: MediCoPrism
description: |
              <p>A blog to explore different scientific  <br />
              perspectives on medical topics and work as a
              <strong><em>prism&nbsp;</em></strong>of knowledge.</p>
url: https://github.com/RiaMedInfo/my-blog
avatar: images/avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /images/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - riya.gemspec

lang: en

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Riya
  url: https://github.com/RiaMedInfo
  email: sotiriastriou@gmail.com
